app/creator/creatorLogin/models.py
from app import db, lm
from werkzeug.security import generate_password_hash, check_password_hash
from flask.ext.login import UserMixin


class Creator(UserMixin ,db.Document):
    username = db.StringField()
    password_hash = db.StringField()

    def set_password(self, password):
        self.password_hash = generate_password_hash(password=password)

    def verify_password(self, password):
        return check_password_hash(password=password, pwhash=self.password_hash)

    @staticmethod
    def register(username, password):
        new_user = Creator(username=username)
        new_user.set_password(password)
        new_user.save()
        return new_user

        

@lm.user_loader
def load_user(id):
    return Creator.objects(id=unicode(id)).first()

app/creator/organizationPage/models.py
from app import db


class Organization(db.Document):
	name = db.StringField(required=True)
	votebox_list=db.ListField(db.ReferenceField('Votebox'))
	@staticmethod
	def create_votebox(name):
		new_votebox = votebox.create_votebox(name, self)


class votebox(db.Document):
	name=db.StringField(required=True)
	organization_id=db.ReferenceField('Organization', required=True)
	
	@staticmethod
	def create_votebox(name, organization_id):
		new_votebox = votebox(name=name , organization_id=organization_id)
		new_votebox.save()
		organization_id.votebox_list.append(new_votebox)

app/creator/voteBoxPage/models.py
from flask import Flask
from flask_mongoengine import MongoEngine
import datetime
from flask import url_for
from app import db


class Candidate(db.EmbeddedDocument):
	name = db.StringField(verbose_nam="cName",required=True)
	vote_count = db.IntField()
	
	
class VoteBox(db.Document):
	created_at = db.DateTimeField(default=datetime.datetime.now, required=True)
	name = db.StringField(verbose_name="Name",required=True)
	description = db.StringField(verbose_nam="Descripton",required=True)
	candidates = db.ListField(db.EmbeddedDocumentField('Candidate'))
	start = db.DateTimeField()
	end = db.DateTimeField()

app/creator/creatorLogin/forms.py
from flask.ext.wtf import Form
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import required, length, EqualTo


class CreatorLogin(Form):
    username = StringField('Username', validators=[required(), length(1, 15)])
    password = PasswordField('Password', validators=[required(), length(1, 30)])
    remember_me = BooleanField('Remember me')
    submit = SubmitField('Submit')


class CreatorSignup(Form):
	username = StringField('Username', validators=[required(), length(1,15)])
	password = PasswordField('Password', validators=[required(), length(1,30)])
	confirm_password = PasswordField('Confirm Password', validators=[EqualTo('password', message='Passwords must match')])
	submit = SubmitField('Submit')

app/__init__.py
from flask import Flask, Blueprint
from flask.ext.mongoengine import MongoEngine
from flask.ext.bootstrap import Bootstrap
from flask.ext.login import LoginManager

app = Flask(__name__)

db = MongoEngine(app)
bootstrap = Bootstrap(app)
lm = LoginManager(app)
lm.login_view = 'creator.login'

app.config["MONGODB_SETTINGS"] = {'DB': "soc_poll"}
app.config["SECRET_KEY"] = "KeepThisS3cr3t"

from creator.creatorLogin import creator as creator_blueprint
app.register_blueprint(creator_blueprint)

from creator.organizationPage import organization_blueprint
app.register_blueprint(organization_blueprint)

if __name__ == '__main__':
	app.secret_key = 'mysecret'
	app.run()

app/creator/creatorLogin/__init__.py
from flask import Blueprint

creator = Blueprint('creator', __name__,template_folder = '/templates')

from . import routes

app/creator/creatorLogin/routes.py
from flask import Flask, render_template, redirect, url_for, flash, request
from flask.ext.login import login_user, logout_user, login_required
from .models import Creator as myCreator
from . import creator
from .forms import CreatorLogin, CreatorSignup

templates_path = 'creatorLogin/'

@creator.route('/creator/login', methods=['GET', 'POST'])
def login():
	form = CreatorLogin()
	if form.validate_on_submit():
		user = myCreator.objects(username=form.username.data).first()
		if user == None or not user.verify_password(form.password.data):
			return redirect(url_for('creator.login'))
		login_user(user, form.remember_me.data)
		return redirect(request.args.get('next') or url_for('creator.main'))
	return render_template('%screator_login.html' % templates_path, form=form)


@creator.route('/creator/logout')
@login_required
def logout():
	logout_user()
	return render_template('%screator_logged_out.html' % templates_path)


@creator.route('/creator/signup', methods=['GET', 'POST'])
def signup():
	warn = ''
	form = CreatorSignup()
	if form.validate_on_submit():
		if myCreator.objects(username=form.username.data): # empty list acts like false
			warn = 'username has been taken. please choose another one.'
			return redirect(url_for('creator.signup'))
		myCreator().register(username=form.username.data, password=form.password.data)
		return render_template('%saccount_created.html' % templates_path)
	return render_template('%screator_signup.html' % templates_path, form=form)

@creator.route('/creator/main')
@login_required
def main():
	return render_template('%screator_logged_in.html' % templates_path)

app/creator/organizationPage/__init__.py
from flask import Blueprint

organization_blueprint = Blueprint('organization_blueprint', __name__,template_folder = 'templates')

from . import view

app/creator/voteBoxPage/views.py
from flask import Blueprint, request, redirect, render_template, url_for
from flask.views import MethodView
from app.voter.voteBoxPage.models import VoteBox, Candidate
from operator import attrgetter
from datetime import datetime
from flask_mongoengine import MongoEngine
from flask_login import login_required
from flask.ext.login import current_user

boxes = Blueprint('boxes',__name__,template_folder='templates')


class BoxView(MethodView):
	def get(self, id):
	 	boxes = VoteBox.objects.get_or_404(id=id)
	 	return render_template('voteBoxPage/box.html',boxes=boxes,id=id,now=datetime.now())


class FinalResultView(MethodView):

	def get(self,id):
		#max(self.allPartners, key=attrgetter('attrOne'))
		loggedIn = False 
		if current_user.is_authenticated:
			loggedIn = True
		boxes = VoteBox.objects.get_or_404(id=id)
		winner = boxes.candidates[0]
		total_count = 0
		for candidate in boxes.candidates:
			total_count += candidate.vote_count
			if candidate.vote_count > winner.vote_count:
				winner = candidate
		return render_template('voteBoxPage/FinalResult.html',boxes=boxes,winner=winner,now=datetime.now(),total_count=total_count,loggedIn=loggedIn)

class MomentaryResultView(MethodView):

	def post(self,id):
		boxes = VoteBox.objects.get_or_404(id=id)
		return render_template('MomentaryResult.html',boxes=boxes)




boxes.add_url_rule('/<id>',view_func=BoxView.as_view('box'))
boxes.add_url_rule('/<id>/result',view_func=FinalResultView.as_view('FinalResult'))
boxes.add_url_rule('/<id>/MomentaryResult',view_func=FinalResultView.as_view('MomentaryResult'))

app/templates/creatorLogin/account_created.html
{% extends "creatorLogin/base.html" %}
{% block page_content %}
	<h1>Your account successfully created!</h1>
{% endblock%}

app/templates/creatorLogin/base.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Poll{% endblock %}

{% block navbar %}
    <nav class="navbar navbar-inverse" role="navigation">
        <div class="container">
            <a class="navbar-brand" href="">
                Poll Example
            </a>
            <ul class="nav navbar-nav">
                <li><a href="">Home</a></li>
                <li><a href="">sth</a></li>
            </ul>>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    {% if current_user.is_authenticated %}
                        <a href="{{ url_for('creator.logout') }}">Logout</a>
                    {% else %}
                        <a href="{{ url_for('creator.login') }}">Login</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </nav>
{% endblock %}

{% block content %}
    <div class="container">
        {% block page_content %}{% endblock %}
    </div>
{% endblock %}

app/templates/creatorLogin/creator_logged_in.html
{% extends "creatorLogin/base.html" %}
{% block page_content %}
	<h1>you have successfully logged in</h1>
{% endblock%}

app/templates/creatorLogin/creator_logged_out.html
{% extends "creatorLogin/base.html" %}
{% block page_content %}
	<h1>you have successfully logged out</h1>
{% endblock%}

app/templates/creatorLogin/creator_login.html
{% extends "creatorLogin/base.html" %}
{% block page_content %}
	<div class="col-md-3" style="margin-bottom:20px">
		{{ wtf.quick_form(form) }}
	</div>
	<div>
		<p style="clear:both;">If you dont have a account, <a href="{{ url_for('creator.signup') }}">click here to signup</a></p>
	</div>
{% endblock%}

app/templates/creatorLogin/creator_signup.html
{% extends "creatorLogin/base.html" %}
{% block page_content %}
	{% from "creatorLogin/form_field.html" import render_field %}
	  <div class="col-md-3">
	  	{{ wtf.quick_form(form) }}
	  </div>
{% endblock%}

app/templates/creatorLogin/form_field.html
{% macro render_field(field) %}
  <dt>{{ field.label }}
  <dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <ul class=errors>
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
  </dd>
{% endmacro %}

app/templates/organizationPage/organ.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{{org.name}} Page </title>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" rel="stylesheet">

    <style>
      .content {padding-top: 80px;}
      .bg-1 {background-color: #ffe6ff;}
      .c{color:#99ffff;}
    </style>
  </head>
  <body class=" bg-1">
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <h2 class="c">
            {{org.name}} Page 
          </h2>
        </div>
        <div class="navbar-collapse">
          <ul class="nav nav-pills navbar-nav navbar-right " style="margin-top:20px">
           </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      <div class="content">
        <div class="table-striped">
       <table class="table">
         <thead>
            <tr>
              <th>VoteBox Name</th>
           </tr>
          </thead>
          <tbody>
        {% for box in org.votebox_list %}
         
        <tr>
          <td>
            <a href="{{url_for('showResults',id=box.name)}}" style="color:#b300b3">
            {{box.name}}</a>
          </td>
        </tr>
        {% endfor %}
        </tbody>
       </table>
     </div>
      </div>
   
    </div>
  </body>
</html>